# Autogenerated by nbdev

d = { 'settings': { 'branch': 'master',
                'doc_baseurl': '/ntest13',
                'doc_host': 'https://hamelsmu.github.io',
                'git_url': 'https://github.com/hamelsmu/ntest13',
                'lib_path': 'ntest13'},
  'syms': {'ntest13.core': {'ntest13.core.foo': ('core.html#foo', 'ntest13/core.py')}}}